enabled: true

exclude:
  - ".github/workflows/**/*"
  - "dep/**"
  - "contrib/**"

changed_paths:
  maximum: 1000
  outcome: error

remote_files: []

auto: false

commit_template: |
  [Restyler] ${restyler.name}

pull_requests: true

comments: false

statuses:
  differences: true
  no_differences: true
  error: true

request_review: none

labels:
  - restyled

ignore_labels:
  - restyled-ignore

restylers_version: stable

restylers:
  - clang-format:
      enabled: false
  - astyle:
      arguments: ["-A1", "-xV", "-S", "-N", "-K", "-Y", "-p", "-xg", "-k1", "-W1", "-xj", "-O"]
  - "*"
