dist: xenial
language: cpp
compiler: clang

git:
  depth: 10

addons:
  apt:
    packages:
      - libboost1.58-dev
      - libboost-filesystem1.58-dev
      - libboost-iostreams1.58-dev
      - libboost-program-options1.58-dev
      - libboost-regex1.58-dev
      - libboost-system1.58-dev
      - libboost-thread1.58-dev
      - libssl-dev
      - libmysqlclient-dev
      - libreadline6-dev
      - zlib1g-dev
      - libbz2-dev

services:
  - mysql

before_install:
  # - chmod +x ./ci/travis-webhook-discord.sh
  - source ./ci/travis-webhook-discord.sh progress

after_success:
  - source ./ci/travis-webhook-discord.sh success

after_failure:
  - source ./ci/travis-webhook-discord.sh failure

install:
  - source ./ci/travis-configure.sh

script:
  - source ./ci/travis-configure.sh
  - source ./ci/travis-install-db.sh
  - source ./ci/travis-build-core.sh