name: import-db
on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false      
    runs-on: ubuntu-18.04
    name: Import DB    
    steps:
      - uses: actions/checkout@v2
      - name: Configure OS and install deps
        run: source ./apps/ci/ci-os-config-db.sh
        env:
          CONTINUOUS_INTEGRATION: true
      - name: Import db
        run: source ./apps/ci/ci-db-import.sh
