name: import-db
on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang7]
    runs-on: ubuntu-18.04
    name: ${{ matrix.compiler }}
    env:
      COMPILER: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: /home/runner/.ccache
          key: ccache:${{ matrix.compiler }}:${{ matrix.modules }}-modules:${{ github.ref }}:${{ github.sha }}
          restore-keys: |
            ccache:${{ matrix.compiler }}:${{ matrix.modules }}-modules:${{ github.ref }}
            ccache:${{ matrix.compiler }}:${{ matrix.modules }}-modules
            ccache:${{ matrix.compiler }}
            ccache
      - name: Configure OS
        run: source ./apps/ci/ci-install.sh
        env:
          CONTINUOUS_INTEGRATION: true
      - name: Import db
        run: source ./apps/ci/ci-import-db.sh