name: import-db
on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang7]
    runs-on: ubuntu-18.04
    name: Import db    
    steps:
      - uses: actions/checkout@v2
      - name: Configure OS
        run: source ./apps/ci/ci-install.sh
        env:
          CONTINUOUS_INTEGRATION: true
      - name: Import db
        run: source ./apps/ci/ci-import-db.sh
